name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  JOB-NAME(init):
  strategy:
    matrix:
      node-version: [23.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Starting Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v5
      with:
        node-version: ${{martrix.node-version}}
      - name: install modules
      run: npm install
      - name: build project
      run: npm run build
