name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  any-name-you-want:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [23.x]

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }} # Fixed typo 'martrix'

      - name: install modules
        run: npm install

      - name: run prettier
        run: npm run ci:format

      - name: run linter
        run: npm run lint

      - name: build project
        run: npm run build
